import { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import PageHero from '../components/ui/PageHero.jsx';

export default function ContactReference() {
  const [sent, setSent] = useState(false);
  return <>
    <PageHero label="CONTACT US" title="Get in Touch for" italic="Free Claim Advice" body="We're here to answer your questions and provide expert guidance on your motor vehicle or accident claim. Reach out for a free, no-obligation conversation—no win no fee." />
    <section className="contact-section section"><div className="contact-details"><span className="eyebrow"><i /> GET IN TOUCH</span><h2>Contact<br /><em>Motor Vehicle Claim</em></h2><p>Reach out today for personalised assistance with your motor vehicle or accident claim. Our team is ready to help you understand your options and take the next steps—no obligation.</p><span className="eyebrow contact-sub-label"><i /> CONTACT DETAILS</span><p>Prefer to email? Use the address below. You can also start your motor vehicle claim directly via the form on our homepage.</p><div className="contact-detail"><span>EMAIL</span><a href="mailto:info@motorvehicleclaim.com">info@motorvehicleclaim.com <ArrowUpRight size={15} /></a></div><div className="contact-detail"><span>PHONE</span><a href="tel:18442282372">(844) 228-2372 <ArrowUpRight size={15} /></a></div><a href="/claim" className="button button-dark contact-claim-button">Start a claim <ArrowUpRight size={15} /></a></div>
      <form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><span className="eyebrow"><i /> SEND A MESSAGE</span><label>Full Name<input required name="name" autoComplete="name" placeholder="Your full name" /></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" rows="6" placeholder="How can we help?" /></label><button className="button button-dark" type="submit">{sent ? 'Message noted' : 'Send Message'} <ArrowUpRight size={15} /></button>{sent && <p className="form-success">Thank you. This demo form does not transmit messages; email info@motorvehicleclaim.com to contact the team.</p>}</form>
    </section>
    <section className="reference-next-step"><span className="eyebrow"><i /> WHAT HAPPENS NEXT</span><h2>After You Get<br /><em>in Touch</em></h2><p>Once you contact us or send a message, a member of our team will review your details and get back to you—usually within one business day. We’ll explain your options, answer your questions, and if you’re eligible, connect you with an attorney for a free consultation. There’s no obligation to proceed; we’re here to help you decide the best next step.</p></section>
    <section className="cta reference-attorney"><div><span className="eyebrow"><i /> TALK WITH US</span><h2>Ready to Start<br /><em>Your Claim?</em></h2></div><div className="cta-aside"><p>We're here to answer your questions and provide expert guidance on your motor vehicle claim.</p><div className="cta-contact"><a href="mailto:info@motorvehicleclaim.com">Email Address&nbsp; info@motorvehicleclaim.com</a><a href="tel:18442282372">Phone&nbsp; (844) 228-2372</a></div></div></section>
  </>;
}
