import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDown, ArrowRight, ArrowUpRight, ShieldCheck, Clock3, HeartHandshake, ChevronDown } from 'lucide-react';
import { services, faqs } from '../data/siteContent.js';
import { Eyebrow, Button } from '../components/ui/Primitives.jsx';
import CTA from '../components/ui/CTA.jsx';
export default function Home(){const[active,setActive]=useState(0);return <><section className="hero"><div className="hero-copy"><div className="hero-kicker"><Eyebrow>INDEPENDENT CLAIM SUPPORT</Eyebrow><span>HERE WHEN IT MATTERS</span></div><h1>A clearer road<br/>to <em>whatâ€™s next.</em></h1><p className="hero-text">An accident can change the shape of your day. Getting clear, considered support shouldnâ€™t make things harder.</p><div className="hero-buttons"><Button>Discuss your claim</Button><a className="text-link" href="#approach">How we help <ArrowDown size={15}/></a></div><div className="hero-proof"><span className="proof-mark"><ShieldCheck size={16}/></span><span>Start with a conversation.<br/><b>No pressure, just a clearer next step.</b></span></div><div className="hero-foot"><span>01 / 03</span><span className="hero-rule"/><span>Here when it matters</span></div></div><div className="hero-visual"><div className="hero-image"><img src="https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1800&q=85" alt="A car travelling on a quiet road through the countryside"/><div className="image-caption"><span>SUPPORT THAT MOVES WITH YOU</span><span>01 â€” A considered first step</span></div><div className="hero-stamp"><span>THE ROAD<br/>AHEAD, WITH<br/><i>SUPPORT.</i></span><ArrowUpRight size={21}/></div></div><div className="hero-float-card"><span className="float-card-icon"><ArrowUpRight size={16}/></span><span>YOUR NEXT STEP<br/><b>Starts here</b></span></div><div className="hero-vertical">MOTOR VEHICLE CLAIM <i>â€”</i> CLEAR, CONSIDERED SUPPORT</div></div><div className="hero-index">MOTOR VEHICLE CLAIM <span>â€” HERE WHEN IT MATTERS</span></div></section>
<section className="trust-strip"><div className="trust-intro">GOOD SUPPORT SHOULD FEEL LIKE THIS</div><div><ShieldCheck/><span>Specialist guidance</span></div><div><Clock3/><span>Support when you need it</span></div><div><HeartHandshake/><span>A human conversation</span></div></section>
<section className="intro section" id="approach"><div className="intro-label"><Eyebrow>A MORE HUMAN APPROACH</Eyebrow><span className="index-large">01</span></div><div className="intro-body"><h2>Make space for<br/>the <em>important things.</em></h2><p>When youâ€™re dealing with the aftermath of an accident, the next steps can feel unclear. We help you understand your options and connect with experienced legal support, so you can focus on what comes next.</p><Button dark={false}>Get to know us</Button></div><div className="intro-note">GOOD ADVICE STARTS<br/>WITH LISTENING <ArrowDown size={16}/></div></section>
<section className="process"><div className="process-image"><img src="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1400&q=85" alt="A person reviewing important documents at a desk"/><div className="process-image-tag">A STEADIER WAY FORWARD</div></div><div className="process-content"><Eyebrow>THE PROCESS, MADE CLEAR</Eyebrow><h2>One step at<br/>a <em>time.</em></h2><p className="section-lede">You donâ€™t need all the answers before you get in touch. Weâ€™ll help you work out where to begin.</p><div className="steps">{[['01','Tell us what happened','Share a few details in your own words.'],['02','Understand your options','Weâ€™ll listen and explain what may be possible.'],['03','Choose what feels right','If you wish, weâ€™ll connect you with a suitable legal partner.']].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight size={17}/></div>)}</div><Button>Start a conversation</Button></div></section>
<section className="services section"><div className="services-head"><div><Eyebrow>HOW WE CAN HELP</Eyebrow><h2>Support for the<br/><em>unexpected.</em></h2></div><p>Every situation is different. Find the kind of support youâ€™re looking for, or simply get in touch and weâ€™ll help you navigate from there.</p></div><div className="service-grid">{services.slice(0,6).map((s,i)=><Link to="/services" className="service-item" key={s}><span>0{i+1}</span><strong>{s}</strong><ArrowUpRight size={17}/></Link>)}</div><Link className="text-link services-link" to="/services">Explore all services <ArrowRight size={16}/></Link></section>
<section className="quote-section"><div className="quote-image"><img src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80" alt="Calm, light-filled space for a conversation"/></div><div className="quote-content"><Eyebrow>HERE FOR THE CONVERSATION</Eyebrow><blockquote>â€œThe first step doesnâ€™t have to be a big one. It just has to be <em>yours.</em>â€</blockquote><span className="quote-caption">A thoughtful conversation can bring the way forward into focus.</span><Button>Speak with our team</Button></div></section>
<section className="faq section"><div className="faq-side"><Eyebrow>A FEW THINGS TO KNOW</Eyebrow><h2>Questions,<br/><em>answered.</em></h2><p>Still wondering about something? Weâ€™re happy to talk it through.</p><a href="mailto:info@motorvehicleclaim.com" className="text-link">Send us a note <ArrowUpRight size={16}/></a></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={`faq-row ${active===i?'open':''}`} key={q}><button onClick={()=>setActive(active===i?-1:i)} aria-expanded={active===i}><span>{q}</span><ChevronDown size={18}/></button>{active===i&&<p>{a}</p>}</div>)}</div></section>
<CTA/></>}


